### ISSUE TITLE
Corrigir método que retorna os cursos que não estão associados a um recurso

### ISSUE THREAD

**Issue by mathunes** [RodrigoSCarvalho/devappcorp#10]
O retorno trás todos os cursos, estando ou não associados a um recurso.

`GET` recurso/cursos

**Comment by RodrigoSCarvalho** [comment]
![image](https://user-images.githubusercontent.com/72170590/174508308-7d2aa445-cbf5-4278-b21f-c9e843ed9a0f.png)

**Comment by RodrigoSCarvalho** [comment]
![image](https://user-images.githubusercontent.com/72170590/174508318-aeeb73db-1f1d-4014-9d0b-132cce8439b6.png)

**Comment by RodrigoSCarvalho** [comment]
Funcionando normalmente aqui
