### ISSUE TITLE
Corrigir método que retorna os eventos que não estão associados a um recurso

### ISSUE THREAD

**Issue by mathunes** [RodrigoSCarvalho/devappcorp#11]
O retorno trás todos os eventos, estando ou não associados a um recurso.

`GET` recurso/eventos

**Comment by RodrigoSCarvalho** [comment]
![image](https://user-images.githubusercontent.com/72170590/174508182-de3fcbea-9a21-4982-84e0-5d959ba95db0.png)

**Comment by RodrigoSCarvalho** [comment]
![image](https://user-images.githubusercontent.com/72170590/174508212-3d40b062-dc37-4cf3-8107-bf28330aa22f.png)

**Comment by RodrigoSCarvalho** [comment]
Funcionando normalmente aqui
