### ISSUE TITLE
Corrigir criação de coleção com recurso

### ISSUE THREAD

**Issue by mathunes** [RodrigoSCarvalho/devappcorp#3]
Ao criar uma coleção com recurso, ambos são criados, porém não são referenciados.

O campo `colecao_id` fica `null` após a criação, impossibilitando a verificação de recursos de uma coleção.

**Comment by RodrigoSCarvalho** [comment]
![image](https://user-images.githubusercontent.com/72170590/174508520-29a89c51-5da1-4a3e-a36f-e86b64bd4443.png)

**Comment by RodrigoSCarvalho** [comment]
![image](https://user-images.githubusercontent.com/72170590/174508590-49098e08-3b2f-4c05-a8d0-137969992a2f.png)

**Comment by RodrigoSCarvalho** [comment]
Funcionando normalmente aqui
