### ISSUE TITLE
Corrigir método para atualizar coleção existente com recurso existente

### ISSUE THREAD

**Issue by mathunes** [RodrigoSCarvalho/devappcorp#4]
A URI do método recebe os ids da coleção e do recurso, porém, o mesmo também exige os dados da coleção no corpo da requisição. Caso seja enviado como vazio, todos os dados da coleção são atualizados para nulo.

**Comment by RodrigoSCarvalho** [comment]
![image](https://user-images.githubusercontent.com/72170590/174509166-6e435bc6-003f-4ec4-bc78-d754f5422a2b.png)

**Comment by RodrigoSCarvalho** [comment]
![image](https://user-images.githubusercontent.com/72170590/174509218-df3bf649-9fcf-471d-afc1-f931e6c1d579.png)

**Comment by RodrigoSCarvalho** [comment]
Funcionando normalmente aqui
